(function(root){
  'use strict';
  function normalize(s){const months=['januar','februar','marz','april','mai','juni','juli','august','september','oktober','november','dezember'];return String(s).normalize('NFKD').replace(/\p{M}/gu,'').toLowerCase().replace(/ß/g,'ss').replace(/−/g,'-').replace(/\b(januar|februar|marz|april|mai|juni|juli|august|september|oktober|november|dezember)\b/g,m=>String(months.indexOf(m)+1)).replace(/\b(?:der|die|das|den|dem|des|ein|eine|einer|einem|einen|eines|im|in|am|an|von|aus|etwa|ungefahr|rund)\b/g,' ').replace(/[^a-z0-9-]+/g,' ').replace(/\b0+(\d)/g,'$1').replace(/\s+/g,' ').trim();}
  function matches(input,answers){const n=normalize(input);return n.length>0&&answers.some(a=>normalize(a)===n);}
  function shuffle(a,rng=Math.random){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
  function pool(questions,history,category,filter){return questions.filter(q=>(category==='all'||q.category===category)&&(filter==='all'||(filter==='unseen'?!history[q.id]:history[q.id]?.correct===false)));}
  function balanced(questions,count){const groups=new Map();for(const q of shuffle(questions)){if(!groups.has(q.category))groups.set(q.category,[]);groups.get(q.category).push(q);}const buckets=shuffle([...groups.values()]),result=[];while(result.length<count&&buckets.some(b=>b.length)){for(const b of buckets){if(b.length&&result.length<count)result.push(b.pop());}}return shuffle(result);}
  function validateSession(s,byId){if(!s||!Array.isArray(s.ids)||!s.ids.length||new Set(s.ids).size!==s.ids.length||s.ids.some(id=>!byId.has(id))||!Number.isInteger(s.index)||s.index<0||s.index>s.ids.length||!Array.isArray(s.results)||s.results.length<s.index||s.results.length>s.index+1)return null;for(let i=0;i<s.results.length;i++){const r=s.results[i];if(!r||r.id!==s.ids[i]||typeof r.correct!=='boolean'||typeof r.input!=='string')return null;}return s;}
  const api={normalize,matches,shuffle,pool,balanced,validateSession};root.QuizEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
